export enum Events {
    SELECTMOVIE = "SELECTMOVIE",
    MARKEDMOVIE = "MARKEDMOVIE",
    TEAMWON = "TEAMWON",
    STEPBYTURN = "STEPBYTURN",
    CATEGORYDEFINED = "CATEGORYDEFINED",
    CREATEROOM = "CREATEROOM",
    USERINTHEROOM = "USERINTHEROOM",
    ADDTIP = "ADDTIP"
}