export enum Events {
    SELECTMOVIE = 'SELECTMOVIE',
    MARKEDMOVIE = 'MARKEDMOVIE',
    TEAMWON = 'TEAMWON',
    STEPBYTURN = 'STEPBYTURN',
    CATEGORYDEFINED = 'CATEGORYDEFINED',
    ADDHIT = 'ADDHIT'
}